### ISSUE TITLE
When I do start seems to be in a loop and never return to the console

### ISSUE THREAD

**Issue by rogelio-blanco** [rburgst/spring-boot-initscript#5]
Hi,

I was doing some testing of the script in amazon aws linux, I place the file in init.d and change all the variables seems to be working but not with the start command.

When I call start I can see in the console where the app is starting but and it shows "Starting boot-log4j2: " but never returns, seems to be in a loop.

Env: Amazon AWS linux, java 8

Do you know how to fix this issue?

**Comment by bedge** [comment]
Try running:

```
DEBUG=1 /etc/init.d/<app name> start
```

This will run the init script with set -x set so you'll see all commands echoed to stdout.

This will echo the exact command line used to start the app.

**Comment by rogelio-blanco** [comment]
Thanks for the help, you were exactly right.   After I change the pattern in the grep command it works :)

I had to change the pattern to '.*Started\s+\S+\s+in.*seconds'

At the end I had this:

```
while { pid_of_spring_boot > /dev/null ; } &&
        ! { tail --lines=+$cnt "$LOG" | grep -q '.*Started\s\+\S\+\s\+in.*seconds' ; } ; do
        sleep 1
    done
```
